const data = [
    {
        id: 0,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    },
    {
        id: 1,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    },
    {
        id: 2,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    },
    {
        id: 113,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    },
    {
        id: 220,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    }, {
        id: 3420,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    }, {
        id: 5540,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    }, {
        id: 11210,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    },
    {
        id: 20221,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    },
    {
        id: 3222220,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    }, {
        id: 51115,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    }, {
        id: 51155,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    },
    {
        id: 3110,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    }, {
        id: 551,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    }, {
        id: 5255,
        brand: 'A10',
        product: 'Phone',
        condition1: 'Acer Aspire 5',
        q_ku_iibinta1: 'Laptop',
        q_isku_bedelka1: 'Hargeisa',
        condition2: 'Used',
        q_ku_iibinta2: 590,
        q_isku_bedelka2: 200,
    },
]

export default data
