const data = [
    {
        id: 0,
        name: 'Xamse Yare',
        number: '+252 63 40034344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'Hargeisa',
        condition: 'Used',
        purchasePrice: 590,
        salePrice: 200,
    },
    {
        id: 1,
        name: 'Yaasir Yare',
        number: '+252 63 40034344',
        itemName: 'Samsung A 70',
        itemType: 'Phone',
        location: 'Baki',
        condition: 'Broken',
        purchasePrice: 320,
        salePrice: 19,
    },
    {
        id: 2,
        name: 'No Name',
        number: '+2526343434344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'Somalia',
        condition: 'Really Broken',
        purchasePrice: 590,
        salePrice: 200,
    },
    {
        id: 113,
        name: 'Xamse Yare',
        number: '+2526343434344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'Gotham',
        condition: 'God Knows',
        purchasePrice: 590,
        salePrice: 200,
    },
    {
        id: 220,
        name: 'Real Donald Trump',
        number: '+2526343434344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'Qaloocan',
        condition: 'Brand New',
        purchasePrice: 590,
        salePrice: 200,
    }, {
        id: 3420,
        name: 'Siciid Gaab',
        number: '+2526343434344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'MI',
        condition: 'Never touched',
        purchasePrice: 590,
        salePrice: 200,
    }, {
        id: 5540,
        name: 'Farmaajo',
        number: '+2526343434344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'NY',
        condition: 'New',
        purchasePrice: 590,
        salePrice: 200,
    }, {
        id: 10,
        name: 'Bill Games',
        number: '+2526343434344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'Hargeisa',
        condition: 'New',
        purchasePrice: 590,
        salePrice: 200,
    },
    {
        id: 20,
        name: 'Batman',
        number: '+2526343434344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'SA',
        condition: 'New',
        purchasePrice: 590,
        salePrice: 200,
    },
    {
        id: 30,
        name: 'Taaxo',
        number: '+2526343434344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'Mars',
        condition: 'New',
        purchasePrice: 590,
        salePrice: 200,
    }, {
        id: 55,
        name: 'Xamse Yare',
        number: '+2526343434344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'Hargeisa',
        condition: 'New',
        purchasePrice: 590,
        salePrice: 200,
    }, {
        id: 555,
        name: 'Xamse Yare',
        number: '+2526343434344',
        itemName: 'Acer Aspire 5',
        itemType: 'Laptop',
        location: 'Sun',
        condition: 'Broken',
        purchasePrice: 590,
        salePrice: 200,
    }
]

export default data
